repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # See also: https://pre-commit.com/hooks.html
      - id: check-ast
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: name-tests-test
        args: [ "--django" ]
      - id: check-executables-have-shebangs
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      # See also: https://github.com/DmytroLitvinov/awesome-flake8-extensions
      - id: flake8
        additional_dependencies: [
          "flake8-bugbear",
          "flake8-comprehensions",
        ]
  - repo: https://github.com/pycqa/pylint
    rev: "v2.15.4"
    hooks:
      - id: pylint
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        args: [ "--load-plugins=pylint_django", "--django-settings-module=coreapp.settings.dev" ]
        additional_dependencies: [
            # pylint dependency
            pylint_django
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        additional_dependencies: [
          # django dependencies
          "django-stubs",
          "djangorestframework-stubs"
        ]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
