[tool.black]
line-length = 79
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
default_section = "THIRDPARTY"
known_first_party = ["api"]
known_third_party = ["django", "django_extensions", "environ", "rest_framework", "settings"]

[tool.pylint.MESSAGE_CONTROL]
disable = """
    line-too-long,
    abstract-method,
    no-member,
"""
enable = "useless-suppression"

[tool.pylint.REPORTS]
reports="no"

[tool.pylint.FORMAT]
max-line-length="79"

[tool.pylint.BASIC]
good-names = "_,i,e,setUp,tearDown,maxDiff"
